# cargo-deny configuration for SQLRustGo
# Security audit and license compliance
# Updated for cargo-deny 0.19+

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
version = 2
yanked = "warn"
ignore = []

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "GPL-3.0-or-later",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
]
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
