[book]
title = "SQLRustGo Documentation"
authors = ["赵天海"]
description = "SQLRustGo - A Rust-implemented SQL-92 Database System"
language = "zh-CN"

[build]
build-dir = "docs/book"
create-missing = true

[output.html]
no-section-label = true
